"""Researched, original website copy. Static HTML is the delivered runtime."""
S = {
 'fl': ('Florida Statutes Chapter 162, Parts I and II', 'https://www.flsenate.gov/Laws/Statutes/2026/Chapter162/All'),
 'tampa': ('Tampa Neighborhood Enhancement: department and contact', 'https://www.tampa.gov/neighborhood-enhancement/about-us'),
 'tampa_code': ('Tampa Code: Chapter 19, property maintenance (§§ 19-49 and 19-50)', 'https://library.municode.com/fl/tampa/codes/code_of_ordinances?nodeId=COOR_CH19PRMASTST'),
 'tampa_cite': ('Tampa Code: Chapter 23.5, supplemental enforcement procedures', 'https://library.municode.com/fl/tampa/codes/code_of_ordinances?nodeId=COOR_CH23.5SUENPR_S23.5-6SUENTO'),
 'tampa_board': ('Tampa Code Enforcement Board', 'https://www.tampa.gov/neighborhood-enhancement/code-enforcement-board-public-nuisance-abatement-board'),
 'tampa_notice': ('Tampa: overgrown lot or yard complaints', 'https://www.tampa.gov/service/overgrown-lot-or-yard-complaint'),
 'hill': ('Hillsborough County: property maintenance codes', 'https://hcfl.gov/residents/property-owners-and-renters/code-violations/property-maintenance-codes'),
 'hill_code': ('Hillsborough Code, Chapter 8, Article IV: Property Maintenance Code', 'https://library.municode.com/fl/hillsborough_county/codes/code_of_ordinances,_part_a?nodeId=HICOCOORLA_CH8BUBURE_ARTIVPRMACO'),
 'hill_agenda': ('Hillsborough 2026 Special Magistrate agenda: PM 12.2 overgrowth cases', 'https://assets.contentstack.io/v3/assets/blteea73b27b731f985/blt90e2c7ba5f847862/05-08-26%20CESM%20Agenda%20East.pdf'),
 'hill_board': ('Hillsborough: Code Enforcement Special Magistrate', 'https://hcfl.gov/councils/code-enforcement-special-magistrate'),
 'hill_ceb': ('Hillsborough: Code Enforcement Board hearings', 'https://hcfl.gov/events/code-enforcement-board-hearing'),
 'hill_lien': ('Hillsborough: apply for a code enforcement lien settlement', 'https://hcfl.gov/residents/property-owners-and-renters/code-violations/apply-for-a-code-enforcement-lien-settlement'),
 'hill_codes': ('Hillsborough: codes and property preservation ordinances enforced', 'https://hcfl.gov/residents/property-owners-and-renters/code-violations/codes-we-enforce'),
 'stpete_code': ('St. Petersburg Code: § 16.40.060.3.1, vegetation maintenance; Chapter 9, enforcement', 'https://library.municode.com/fl/st._petersburg/code_of_ordinances'),
 'stpete_update': ('St. Petersburg: 2024–2025 residential land-development code update', 'https://cms5.revize.com/revize/stpete/Residential%20LDR%20Update%202024-2025.pdf'),
 'stpete_budget': ('St. Petersburg FY 2026 budget materials: Codes Compliance Assistance', 'https://cms5.revize.com/revize/stpete/2025-07-31%20COW%20Agenda%20Packet.pdf'),
 'stpete_cases': ('St. Petersburg: official code enforcement case search', 'https://stpe-egov.aspgov.com/Click2GovCE/casesearch.html'),
 'stpete_sm': ('St. Petersburg: Special Magistrate rules of procedure', 'https://cms5.revize.com/revize/stpete/Residents/codes/docs/SM%20Rules%20of%20Procedure.pdf'),
 'clearwater': ('Clearwater: report a violation and understand the process', 'https://www.myclearwater.com/My-Government/0-City-Departments/Planning-Development/Code-Compliance/Report-a-Code-Violation'),
 'clearwater_board': ('Clearwater: Municipal Code Enforcement Board', 'https://www.myclearwater.com/My-Government/0-City-Departments/Planning-Development/Code-Compliance/Municipal-Code-Enforcement-Board'),
 'clearwater_code': ('Clearwater Community Development Code', 'https://library.municode.com/fl/clearwater/codes/community_development_code'),
 'clearwater_affidavit': ('Clearwater 2026 enforcement affidavit quoting §§ 3-1503.B.7 and B.8', 'https://clearwater.legistar.com/View.ashx?GUID=A7D98680-F8B0-4028-A15C-14CAB560BC56&ID=15129598&M=F'),
 'clearwater_guide': ('Clearwater: A Citizens Guide to Code Enforcement', 'https://www.myclearwater.com/files/sharedassets/public/v/2/planning-amp-development/documents/code-enforcement/code_compliance_handbook_b.pdf'),
 'pinellas': ('Pinellas County: common violations and yard maintenance', 'https://pinellas.gov/enforcement-codes/'),
 'pinellas_code': ('Pinellas County Code § 58-331: lot-clearing prohibitions', 'https://library.municode.com/fl/pinellas_county/codes/code_of_ordinances?nodeId=PTIIPICOCO_CH58EN_ARTIXLOCL_S58-331PR'),
 'pinellas_sm': ('Pinellas County: Special Magistrate hearings', 'https://pinellas.gov/special-magistrate-administrative-division/'),
 'pinellas_lien': ('Pinellas County: request lien reduction', 'https://pinellas.gov/services/request-reduction-form/'),
 'bradenton': ('City of Bradenton: Code Enforcement Division', 'https://cityofbradenton.com/code'),
 'bradenton_code': ('Bradenton Code: §§ 18-240 and 18-241, property maintenance', 'https://library.municode.com/fl/bradenton/codes/code_of_ordinances'),
 'bradenton_amend': ('Bradenton: Ordinance 3096 property maintenance code amendments', 'https://cityofbradenton.com/vertical/sites/%7B98CFEB92-7265-45CB-AF6F-7115C2CD7C81%7D/uploads/Planning_-_Ordinance_3096.pdf'),
 'bradenton_sm': ('Bradenton: Code Enforcement Special Magistrate', 'https://cityofbradenton.com/codeenforcement'),
 'manatee': ('Manatee County: Code Enforcement Do’s and Don’ts', 'https://www.mymanatee.org/connect/news-and-information/news-and-information/article-detail/code-enforcement-division-posts/2025/07/07/code-enforcement-do%27s-and-don%27ts'),
 'manatee_code': ('Manatee County Code § 2-9-103: definitions, Property Maintenance and Structural Standards', 'https://library.municode.com/fl/manatee_county/codes/code_of_ordinances?nodeId=PTIIMACOCOOR_CH2-9COIM_ARTVIPRMASTST_S2-9-103DE'),
 'manatee_process': ('Manatee County: Code Enforcement Case Process', 'https://www.mymanatee.org/connect/news-and-information/news-and-information/article-detail/code-enforcement-division-posts/2025/07/29/code-enforcement-case-process'),
 'manatee_sm': ('Manatee County: Code Enforcement Special Magistrate', 'https://www.mymanatee.org/government/government-information/advisory-boards/advisory-board-detail/code-enforcement-special-magistrate'),
 'manatee_scope': ('Manatee County: Code Enforcement 101', 'https://www.mymanatee.org/connect/news-and-information/news-and-information/article-detail/code-enforcement-division-posts/2025/07/16/code-enforcement-101'),
}

def cite(key, label=None):
    title, url = S[key]
    return f'<a href="{url}" rel="external">{label or title}</a>'

def section(id, title, body): return (id, title, body)

GUIDES = [
dict(slug='what-counts-as-overgrown', label='What counts as a violation', title='What counts as an overgrown-property violation?', description='Tampa Bay grass, weeds, brush and debris rules explained. Understand height limits, vacant lots, swales and the code section on your notice.', intro='A yard can violate local rules because of its height, its condition, or what it blocks. Start with the ordinance on your notice—not a height limit from a neighboring city.', answer='There is no single Tampa Bay grass-height rule. The issuing city or county sets the standard. A cleanup may need to address grass, underbrush, debris and an adjoining right-of-way, not just the front lawn.', sources=['pinellas','pinellas_code','clearwater_affidavit','manatee','tampa_code','hill_code','stpete_code','bradenton_code'], sections=[
section('height','Height is only part of the rule',f'''<p>Some local rules use a measurable height; others also address untended vegetation, vermin, fire hazards or obstructed access. A maintained landscape bed is not necessarily treated like an abandoned patch of weeds. The plant type, the portion of the lot affected and any applicable exception matter.</p><p>For example, {cite('pinellas','Pinellas County’s official summary')} describes grass and weeds reaching 12 inches over the majority of the property. {cite('clearwater_affidavit','Clearwater cites § 3-1503.B.7')} for growth over 12 inches. {cite('manatee','Manatee County’s guidance')} says to keep grass below 16 inches. These are different local rules, not interchangeable mowing targets.</p><p>Read the exact section, definitions and exceptions that apply to your parcel. Our <a href="/local-codes/">jurisdiction guides</a> identify the official code and enforcement office. Where we cannot confirm a current numeric limit, we do not publish a guessed one.</p>'''),
section('brush','Weeds, brush and debris can be separate violations','''<p>Vines on fencing, dense underbrush, fallen limbs and accumulated yard waste may require more than a standard lawn cut. A notice can list both an overgrowth section and a trash or debris section. Finishing one item does not necessarily resolve the other.</p><ul><li>Read every cited item and inspect the back and side yards as well as the street frontage.</li><li>Identify debris hidden in the growth before equipment enters the property.</li><li>Ask what must be removed, what may remain as mulch and how waste must be placed for authorized collection.</li><li>Do not move the problem to the street, a drainage ditch or an adjacent lot.</li></ul><p>Tell the cleanup crew about wire, concrete, dumped trash, stumps, soft ground and other obstacles. A bush hog cuts vegetation; it is not a substitute for collecting hidden debris.</p>'''),
section('vacant','Vacant does not mean exempt','''<p>A vacant house still has a yard to maintain. An undeveloped lot may be subject to different rules from a developed residential parcel, and large, agricultural, conservation or environmentally sensitive parcels may require a closer look at scope and exceptions.</p><p>Before ordering an entire wooded lot cleared, ask the officer which area and which vegetation must be addressed. An overgrowth notice is not blanket permission to remove protected trees, disturb wetlands, alter drainage or clear a conservation area. Keep those questions separate from ordinary mowing.</p>'''),
section('right-of-way','Check the sidewalk, swale and right-of-way','''<p>The required maintenance area may extend beyond a fence or surveyed property line. Some jurisdictions place maintenance duties on the abutting owner or occupant. Other areas belong to an agency or are subject to easements. Ask the officer to identify the exact strip on a photo or parcel map.</p><p>Keep sidewalks passable and ask about sight-line issues at corners. Do not fill or regrade a swale to make mowing easier. If access is unsafe or boundaries are uncertain, document the condition and request clarification before work.</p>'''),
section('scope','Turn the notice into a cleanup scope','''<ol><li>Record the government’s name, case number, cited sections and deadline.</li><li>Photograph each affected area, including side yards and any cited frontage.</li><li>Confirm the work area, disposal requirements and any protected features.</li><li>Arrange mowing, brush clearing and debris removal as needed.</li><li>Send completion evidence and <a href="/guides/proving-compliance/">request reinspection and written closure</a>.</li></ol><p>We can quote the cleanup and provide before/after documentation. The enforcing government decides whether the cited conditions comply.</p>''')]),

dict(slug='enforcement-timeline',label='The enforcement timeline',title='From the first notice to a closed case.',description='How overgrown-property enforcement works in Tampa Bay: inspections, deadlines, hearings, fines, liens, government mowing and written case closure.',intro='Most cases offer a chance to fix the property. Know which stage you are in, because a courtesy warning, a hearing notice and a recorded lien require different responses.',answer='Find the compliance date and hearing date on your notice. Contact the assigned officer, arrange the work, and request written confirmation after reinspection. Do not assume every case follows every step below.',sources=['fl','manatee_process','pinellas','tampa_cite'],sections=[
section('stages','A common administrative path',f'''<ol class="timeline"><li><h3>Complaint or proactive inspection</h3><p>An officer inspects the condition. A case may start without a neighbor complaint. Florida generally requires a complainant’s name and address, with statutory exceptions for imminent threats.</p></li><li><h3>Courtesy contact, when used</h3><p>A door hanger or warning may explain what to correct. A separate courtesy warning is not guaranteed in every case.</p></li><li><h3>Notice of violation and compliance date</h3><p>The notice identifies the rule and corrective action. Under {cite('fl','§ 162.06(2)')}, an ordinary Part I case generally provides a reasonable time to correct; it does not establish one universal grass-cutting deadline.</p></li><li><h3>Reinspection</h3><p>The officer checks the cited conditions. If the work is incomplete, the case can move forward. Send evidence promptly rather than waiting for the officer to happen past.</p></li><li><h3>Hearing and written order</h3><p>A board or Special Magistrate considers evidence and may set a compliance date and fine consequences. A hearing can still occur after a late cleanup.</p></li><li><h3>Daily fine, if imposed</h3><p>For an ordinary first violation, fines under § 162.09 can run for days beyond the ordered compliance date. Repeat violations can be treated differently.</p></li><li><h3>Recorded lien and potential collection</h3><p>A recorded fine order can become a lien. Nonpayment can lead to further collection, potentially including a foreclosure action subject to legal limits. See the <a href="/guides/liens-and-fine-reductions/">lien guide</a>.</p></li></ol>'''),
section('branches','Government mowing is a separate possible branch',f'''<p>Local abatement procedures can allow the city or county to arrange cleanup and charge the responsible property or owner. Do not assume a government mower must wait for the entire administrative-hearing sequence above. The applicable local ordinance and abatement notice control.</p><p>{cite('pinellas','Pinellas County explicitly warns')} that it may hire a mowing or debris-removal contractor and place an interest-accruing lien for the cost. An abatement bill and an administrative fine are different charges; resolving one may leave the other outstanding.</p><p>A <a href="/guides/civil-citations/">civil citation or notice to appear in court</a> is another possible path. It has its own instructions. Do not treat a citation as merely another reminder to mow.</p>'''),
section('faster','When the process can move faster',f'''<p>{cite('fl','Section 162.06(3)–(4)')} makes different provisions for repeat violations and serious threats or irreversible conditions. In a repeat case, the officer need not give another reasonable correction period before requesting a hearing. A prior violation at a different location may matter under the statutory definition.</p><p>Do not count on a fresh warning each time grass grows back. Start recurring maintenance while the property is still in good condition.</p>'''),
section('action','What to do at your stage','''<div class="table-wrap"><table><caption>Match your action to the document</caption><thead><tr><th scope="col">What you received</th><th scope="col">Your next step</th></tr></thead><tbody><tr><td>Warning or violation notice</td><td>Confirm the required work and deadline; request any extension early.</td></tr><tr><td>Notice of hearing</td><td>Prepare evidence and attend unless the hearing is formally canceled.</td></tr><tr><td>Order or fines running</td><td>Arrange compliance, confirm the effective compliance date and obtain an updated balance.</td></tr><tr><td>Lien or abatement bill</td><td>Get a payoff and ask about reduction or release requirements separately from cleanup.</td></tr><tr><td>Court citation or summons</td><td>Follow the court response instructions promptly and seek legal advice if needed.</td></tr></tbody></table></div><p>A booking request, invoice or pending extension request does not pause enforcement. Get any changed deadline or canceled hearing confirmed by the authorized office.</p>''')]),

dict(slug='request-an-extension',label='Ask for more time',title='Need more time? Ask before the deadline.',description='How to request an overgrown-property code enforcement extension in Tampa Bay, with a practical request template, supporting documents and follow-up steps.',intro='A specific plan is more useful than “I’ll get to it.” Tell the officer what is scheduled, what is holding up the work and the date you can realistically finish.',answer='Contact the officer listed on your notice before the compliance date. Ask who has authority to extend it, propose a specific completion date, attach supporting proof and request a written response. Approval is not automatic.',sources=['fl','bradenton','hill_board','manatee_sm'],sections=[
section('contact','Start with the assigned officer','''<p>Use the officer’s direct contact information on the notice. Have the case number and property address ready. If you cannot reach the officer, contact the issuing department and ask who is covering the case. A cleanup company can supply a work estimate and schedule; it cannot grant an extension.</p><p>Tell the office whether this is an initial violation deadline, a deadline in a board or Magistrate order, a court response date or a government-abatement notice. The person who can change one date may not have authority to change another.</p><p>If an order has already been entered, ask whether an extension requires a motion, application or another hearing. Do not assume a phone conversation changes a written order.</p>'''),
section('proof','Send a short, documented plan','''<ul><li>The case number, address and your relationship to the property.</li><li>The specific date you are requesting, not an open-ended delay.</li><li>A contractor estimate or confirmed work date, if available.</li><li>Dated photos of work already completed and remaining conditions.</li><li>A factual explanation of the obstacle: access, documented illness, estate authority, equipment availability or unsafe ground conditions.</li><li>A plan to remove debris and prevent the same condition returning.</li></ul><p>Keep personal documentation relevant and limited. Ask the agency how to submit sensitive information before sending medical or financial records. A promise from a contractor is not proof that the government has accepted a new deadline.</p>'''),
section('wording','A plain-English extension request','''<div class="sample-message"><p>Subject: Extension request — Case [number], [property address]</p><p>I am responsible for the property at [address]. The notice lists a compliance deadline of [date]. I am arranging [specific cleanup work] and request an extension through [new date] because [brief factual reason].</p><p>[Contractor/work crew] is scheduled for [date]. I have attached [estimate, scheduling confirmation or progress photos]. The remaining work is [list].</p><p>Please let me know whether you can approve this request or whether a formal request to the board, Magistrate or court is required. Please confirm the applicable deadline in writing and tell me whether the scheduled hearing or any fines will be affected.</p></div>'''),
section('follow-up','If you do not get an answer','''<p>Follow up before the original deadline and document the date and method of each contact. Continue the work you can safely and lawfully complete. The existing deadline remains your working deadline until an authorized decision changes it.</p><p>If your request is denied, ask what can still be corrected on time and whether staged completion is acceptable. If a hearing is scheduled, prepare to explain the work done, the reason for delay and your remaining plan. Bring the correspondence; do not skip the hearing because you asked for more time.</p><p>If a court response or appeal deadline is involved, contact a Florida lawyer or the relevant court promptly. This cleanup guide does not calculate or extend legal filing deadlines.</p>'''),
section('cleanup','Coordinate the cleanup with the revised deadline','''<p>Once a work date is confirmed, share it with the officer and ask how to request reinspection. Arrange access, identify disposal needs and photograph the initial condition. After completion, send dated photos and the invoice. Ask for the recorded compliance date and case status.</p><p>If the deadline is within seven days or has passed, <a href="tel:+18136712757">call 813-671-2757</a> to discuss cleanup availability. Availability and the required scope must be confirmed before a job is scheduled.</p>''')]),

dict(slug='fines-and-costs',label='Fines and cleanup costs',title='How code enforcement fines add up.',description='Understand Florida code enforcement daily fines, first and repeat violations, local higher limits, abatement bills and what stops fines from accruing.',intro='A daily fine, a civil citation and a bill for government mowing are different things. Start by identifying the charge and the order that authorizes it.',answer='Under Florida’s standard Part I limits, fines can be up to $250 per day for a first violation and $500 per day for a repeat violation. Qualifying governments can adopt higher limits. These are legal ceilings, not an automatic price for an overgrown yard.',sources=['fl','tampa_cite','pinellas','manatee_process'],sections=[
section('limits','The state framework is not a local price list',f'''<div class="table-wrap"><table><caption>Florida Statutes § 162.09(2): administrative fine limits</caption><thead><tr><th scope="col">Authority</th><th scope="col">First violation</th><th scope="col">Repeat violation</th><th scope="col">Irreparable or irreversible</th></tr></thead><tbody><tr><td>Standard limits, § 162.09(2)(a)</td><td>Up to $250/day</td><td>Up to $500/day</td><td>Up to $5,000/violation</td></tr><tr><td>Locally adopted higher authority, § 162.09(2)(d)</td><td>Up to $1,000/day/violation</td><td>Up to $5,000/day/violation</td><td>Up to $15,000/violation</td></tr></tbody></table></div><p>The second row is available only where a government with at least 50,000 residents has adopted the required ordinance by the specified vote. Population alone does not establish a local fine schedule. {cite('fl','Read § 162.09(2) for the conditions')}.</p><p>The amount actually imposed depends on the local authority and the order in your case. Ordinary overgrowth that can be corrected should not simply be assumed to be an irreversible violation. A special historic-demolition provision in § 162.09(2)(e) is outside this mowing guide.</p>'''),
section('running','When the daily clock starts and stops',f'''<p>For an ordinary first violation under Part I, § 162.09(1) ties daily fines to continued noncompliance after the board’s ordered date. For a repeat violation, fines may run from the date the inspector finds that it occurred. A missed courtesy deadline is not, by itself, proof that a particular daily fine has already been imposed.</p><p>Under § 162.09(3), accrual continues until compliance or judgment in the specified collection suit, whichever comes first. Promptly document the cleanup and obtain the government’s written compliance determination. Ask which date it recognizes; do not rely on a contractor’s completion date alone to settle a disputed balance.</p><div class="notice-box"><p><strong>Example only:</strong> If an order sets $100 per day and the counted noncompliance period is 12 days, the daily-fine component is $1,200. This is arithmetic, not a quoted local fine. Costs and other charges may be additional.</p></div>'''),
section('repeat','A repeat case is not just a second warning',f'''<p>{cite('fl','Section 162.04(5)')} defines a Part I repeat violation by reference to a previous finding of a violation of the same code provision within five years. It can involve a different location. Simply receiving two complaint letters is not the complete legal test.</p><p>The repeat-case procedures can dispense with another reasonable correction period. A civil-citation program can also have its own local repeat definition, so check the enforcement track rather than importing the Part I definition into every ticket.</p>'''),
section('costs','The balance can include more than a fine','''<ul><li><strong>Enforcement costs:</strong> Part I provides for recovery of prosecution costs when the government prevails, and applicable local provisions may authorize additional costs.</li><li><strong>Abatement costs:</strong> Contractor mowing, debris removal and authorized administrative charges can create a separate bill.</li><li><strong>Recording, release and collection costs:</strong> Lien-related expenses may apply under the relevant authority.</li><li><strong>Interest:</strong> Confirm whether it applies to your particular lien or assessment and how a payoff is calculated.</li></ul><p>Request an itemized balance that separates daily fines, costs, interest and abatement charges. A payment for one case may not satisfy another case at the same address.</p>'''),
section('reduce','Cleanup and fine reduction are separate steps','''<p>Correcting the violation helps stop the problem from getting more expensive, but it does not automatically wipe out the existing balance. Section 162.09(2)(c) permits fine reduction; it does not promise one. Follow the local application and approval process.</p><p>Keep photos, invoices, scheduling records and your communications with the officer. Those records help establish what was corrected and when. See <a href="/guides/liens-and-fine-reductions/">liens and fine reductions</a> for preparing a reduction request.</p>''')]),

dict(slug='hearings-and-appeals',label='Prepare for a hearing',title='What happens at a code enforcement hearing?',description='Prepare for a Tampa Bay Code Enforcement Board or Special Magistrate hearing: evidence, local hearing bodies, compliance orders and Florida appeal rights.',intro='A hearing is your opportunity to respond to the alleged violation and put your evidence in the record. Prepare even if the cleanup has already been completed.',answer='Read the notice to identify the hearing body, date, location and submission rules. Bring the notice, a short chronology, dated photos, invoices and correspondence. Do not assume a cleanup or extension request cancels your appearance.',sources=['fl','tampa_board','hill_board','hill_ceb','stpete_budget','stpete_sm','clearwater_board','clearwater_guide','pinellas_sm','bradenton_sm','manatee_sm'],sections=[
section('who','Board, Magistrate or court?',f'''<p>A Code Enforcement Board is a panel. A Special Magistrate is an individual appointed to hear administrative code cases; § 162.03(2) allows an alternative system with the board’s status and powers. Neither should be confused with the judge hearing a county-court citation.</p><div class="table-wrap"><table><caption>Administrative hearing bodies identified in official local materials</caption><thead><tr><th scope="col">Jurisdiction</th><th scope="col">Published process</th></tr></thead><tbody><tr><td>City of Tampa</td><td>{cite('tampa_board','Code Enforcement Board')}; follow the hearing assignment on your notice.</td></tr><tr><td>Hillsborough County</td><td>{cite('hill_board','Special Magistrate')} and {cite('hill_ceb','Code Enforcement Board')} processes.</td></tr><tr><td>St. Petersburg</td><td>{cite('stpete_budget','Board and Special Magistrate processes')}, as well as citation/court enforcement.</td></tr><tr><td>Clearwater</td><td>{cite('clearwater_board','Municipal Code Enforcement Board')}; the city handbook also identifies a Special Magistrate option.</td></tr><tr><td>Pinellas County</td><td>{cite('pinellas_sm','Special Magistrate')}.</td></tr><tr><td>Bradenton</td><td>{cite('bradenton_sm','Special Magistrate')}.</td></tr><tr><td>Manatee County</td><td>{cite('manatee_sm','Special Magistrate')}.</td></tr></tbody></table></div><p>Assignment, meeting locations and schedules can change. The specific notice and current agency agenda are your guide; this table is not a hearing calendar.</p>'''),
section('prepare','Build a small, organized evidence packet','''<ol><li><strong>Notice and case details:</strong> all pages, attachments, the address and each cited section.</li><li><strong>One-page chronology:</strong> when you learned of the notice, contacted the officer, arranged work and completed it.</li><li><strong>Before/after photographs:</strong> wide views and close views of every cited condition, with reliable dates and matching angles.</li><li><strong>Invoice and work description:</strong> the property address, work performed and completion date.</li><li><strong>Correspondence:</strong> extension decisions, access issues, progress reports and any reinspection findings.</li></ol><p>Ask how and when to submit digital files, whether printed copies are required, and whether remote attendance or an authorized representative is allowed. Do not assume you can simply display photos from your phone. An entity or estate may have representation issues that warrant legal advice.</p>'''),
section('hearing','During and after the hearing',f'''<p>Under {cite('fl','§ 162.07')}, testimony is under oath and recorded. The officer and alleged violator can present testimony. Formal evidence rules do not apply, but fundamental due process must be observed. The decision results in findings and an order.</p><p>Address each cited condition calmly. Explain what was completed, identify the evidence and make a specific request if more time is needed. If you disagree with the allegation, identify the factual or code issue instead of assuming recent mowing resolves every dispute.</p><p>Get the written order. Confirm any new compliance date, daily fine, cost assessment and reinspection requirement. A late correction can still leave the case eligible for a hearing under § 162.06(2); ask the office whether attendance is still required.</p>'''),
section('appeal','Appeal rights have a short clock',f'''<div class="notice-box"><p><strong>Part I administrative appeal:</strong> {cite('fl','§ 162.11')} provides an appeal to circuit court within 30 days of execution of the order. Review is based on the administrative record; it is not a new trial.</p></div><p>Do not measure this deadline from the day you happen to read the order without checking the applicable law. A fine-reduction request or a call to the officer is not a substitute for filing an appeal. Do not assume enforcement is stayed merely because you are considering or filing one.</p><p>Contact a Florida lawyer promptly if you wish to challenge an order, dispute service, preserve an appellate issue or seek a stay. A county-court judgment follows its own appeal procedures; do not apply the administrative appeal rule indiscriminately.</p>''')]),

dict(slug='civil-citations',label='Citations and county court',title='A citation is different from a cleanup notice.',description='Florida Chapter 162 Part II civil citations and county court explained for Tampa Bay property owners, including response dates and notices to appear.',intro='If your paperwork tells you to pay a civil penalty, contest a citation or appear in court, deal with those instructions separately from getting the yard cut.',answer='A code violation does not automatically become a court case after a set number of days. Local government may use a civil-citation process under Chapter 162 Part II. Your citation identifies how to pay or contest it and the applicable deadline.',sources=['fl','tampa_cite','bradenton','manatee_process'],sections=[
section('identify','Identify which document you actually have','''<div class="table-wrap"><table><thead><tr><th scope="col">Document</th><th scope="col">What it usually asks you to do</th></tr></thead><tbody><tr><td>Notice of violation</td><td>Correct stated conditions by a specified date.</td></tr><tr><td>Administrative hearing notice</td><td>Appear before a board or Special Magistrate.</td></tr><tr><td>Civil citation</td><td>Follow the stated payment or contest procedure for an alleged civil infraction.</td></tr><tr><td>Notice to appear, summons or court notice</td><td>Follow the specified court appearance or response instructions.</td></tr></tbody></table></div><p>Read the document’s heading, issuing agency, ordinance, case number and forum. A notice can mention several consequences, so if the track is unclear, call the office identified on it and the court clerk when a court case number is listed.</p>'''),
section('part-two','What Florida’s civil-citation statute says',f'''<p>{cite('fl','Section 162.21(3)')} permits an authorized officer to issue a citation, based on personal investigation and reasonable cause, for a civil infraction that county court will hear. Before an ordinary citation, the officer gives notice and a reasonable correction period of no more than 30 days. Repeat, serious-threat and irreversible conditions have exceptions.</p><p>“No more than 30 days” is a ceiling in that procedure—not a promise that every property owner gets 30 days. Follow the actual deadline. Local government must adopt the applicable implementation and penalty provisions.</p><p>Under § 162.21(5), this civil-infraction procedure has a maximum civil penalty of $500 and a lesser penalty for not contesting. Check the local schedule and citation for the amount and applicable costs; this is not the same as the daily administrative fine limits in § 162.09.</p>'''),
section('local','Local examples of different enforcement tracks',f'''<p>{cite('tampa_cite','Tampa Code Chapter 23.5')} expressly implements Part II and places violations governed by that chapter in county court. It sets local citation procedures and classified penalties. Use the exact provision on the ticket; do not assume one citywide fine applies to every vegetation issue.</p><p>{cite('bradenton','Bradenton’s Code Enforcement Division')} says it uses both a Special Magistrate and the citation process. {cite('manatee_process','Manatee County’s case-process page')} describes citations, notices to appear and referral to a Special Magistrate as possible routes. These are alternatives or related steps, not proof that every case follows one fixed ladder.</p>'''),
section('respond','Respond even if you have already mowed','''<p>Cutting the grass does not automatically withdraw a citation already issued. Payment, a contest request, a dismissal and administrative compliance are separate actions. Ask for written confirmation of any withdrawal and check court status when a case has been filed.</p><p>Under § 162.21, failing to pay or appear as required can waive the right to contest and allow judgment up to the maximum civil penalty. Read the instructions immediately. If you plan to contest liability, seek legal advice before choosing a payment option with consequences you do not understand.</p><p>Keep the citation, photographs, invoice and all communications. Do not send a contractor to a hearing assuming that they can represent you.</p>'''),
section('appear','Take a notice to appear seriously',f'''<p>Section 162.23 addresses a distinct notice-to-appear procedure. It generally calls for a written correction notice with a period of at least 5 and no more than 30 days before a notice to appear, subject to its stated exceptions. That rule should not be confused with § 162.21’s civil-citation provisions.</p><p>Part II also includes municipal-ordinance enforcement provisions beyond civil infractions. A court document should not be dismissed as “just a mowing ticket.” Confirm the nature of the proceeding and required response with the court and, where appropriate, a Florida lawyer.</p>''')]),

dict(slug='liens-and-fine-reductions',label='Liens and fine reductions',title='The yard is clear. What about the lien?',description='Florida code enforcement liens, fine reduction and mitigation in Tampa Bay. Learn what compliance changes, how to request a reduction and how to verify release.',intro='Cleanup, a zero balance and a released lien are three different milestones. Keep going until the government confirms what remains and the public record reflects any required release.',answer='Compliance does not automatically erase an existing fine or recorded lien. Request the current balance, identify the local reduction procedure, submit supporting records and obtain written approval. Confirm payment and a recorded release where required.',sources=['fl','hill_lien','pinellas_lien','pinellas'],sections=[
section('attach','How a code enforcement lien can attach',f'''<p>Under {cite('fl','§ 162.09(3)')}, recording a certified fine order can create a lien against the violation property and other real or personal property owned by the violator. The effect on a particular owner or property can involve legal exemptions and title questions.</p><p>Government-abatement charges may instead arise under a local mowing or nuisance-assessment procedure. Ask whether your balance is an administrative fine lien, an abatement assessment, a court judgment or more than one obligation. The same reduction rules do not necessarily apply to each.</p><p>Get the case number, recording information and an itemized payoff. A database entry marked “complied” does not necessarily establish that the debt is paid or the lien released.</p>'''),
section('reduce','Request a reduction or mitigation review',f'''<p>Section 162.09(2)(c) allows a board to reduce a fine. Local rules determine how to apply, who decides and what documentation is required. A cleanup company can document its work but cannot promise a settlement or act as your lawyer.</p><ol><li>Complete all cited corrective work and get the compliance determination.</li><li>Request the reduction application and an itemized balance.</li><li>Collect before/after photos, invoices, dates and relevant communications.</li><li>Explain the circumstances concisely and document corrective effort.</li><li>Submit the required signed or notarized materials through the official channel.</li><li>Get the decision, payment conditions and release instructions in writing.</li></ol><p>Do not assume a requested percentage will be approved. Enforcement costs, abatement bills and interest may receive different treatment from the fine.</p>'''),
section('local','Two local processes to know',f'''<h3>Hillsborough County</h3><p>{cite('hill_lien','The county’s settlement instructions')} require compliance before settlement or release. The property owner or authorized representative submits a complete, signed application with notarized signatures through the official submission channel. Qualifying homesteaded hardship situations may receive consideration with supporting documents. Read the county’s current instructions for where and how to submit.</p><h3>Pinellas County</h3><p>{cite('pinellas_lien','The county’s reduction page')} says a compliant property owner may be eligible and also provides a route for a prospective new owner of a noncompliant property. That does not guarantee a reduction or mean a buyer can ignore outstanding work. Submit the requested facts and wait for the county’s determination.</p><p>For a city case, use that city’s procedure. A county’s reduction form does not settle a Tampa, Clearwater, St. Petersburg or Bradenton lien merely because the property lies within the county.</p>'''),
section('closing','Sales, refinancing and inherited property','''<p>Tell your closing agent or title professional about every known notice, order and lien early. Obtain a current payoff and ask whether additional cases, recorded orders or assessments exist. A search for one case number is not a complete title examination.</p><p>If ownership is being transferred while an enforcement proceeding is pending, § 162.06(5) imposes specific disclosure and notification duties in the situation it covers. Get transaction-specific advice; a sale does not automatically dismiss the proceeding.</p><p>Do not promise a closing date based solely on the cleanup date. Reinspection, reduction review, payment processing and recording a release can each take additional time.</p>'''),
section('foreclosure','Foreclosure risk—and the homestead distinction',f'''<p>Section 162.09(3) allows the board, after an unpaid lien has been recorded for three months, to authorize the local government’s attorney to pursue foreclosure or a money judgment. It is not automatic foreclosure on day 91.</p><p>The same statute bars foreclosure of a Part I lien on constitutionally protected homestead property and limits the money-judgment provision for constitutionally protected property. Do not assume that protection cancels the debt, releases the lien or necessarily governs a different type of local assessment.</p><p>Section 162.10 generally limits a Part I lien to 20 years from recording, with a litigation exception. Do not calculate your rights from that headline alone. Get a Florida lawyer’s advice if you receive a foreclosure complaint, collection lawsuit or disputed title report.</p>'''),
section('release','Verify the finish line','''<p>After an approved settlement or full payment, keep the payment receipt and obtain the satisfaction or release. Verify the recording information with the issuing office or your title professional. Ask separately whether the enforcement case is closed and whether recurring inspection or maintenance obligations remain.</p><p>Arrange ongoing mowing so new growth does not create another case while a settlement is being processed.</p>''')]),

dict(slug='proving-compliance',label='Prove it is fixed',title='Make the cleanup count. Document it.',description='How Tampa Bay owners prove an overgrown-property violation is corrected: dated photos, invoices, reinspection and written case closure.',intro='The last pass with the mower is not the last step. Give the officer a clear record of what changed and ask for a formal compliance determination.',answer='Send the case number, property address, dated completion photos and an itemized invoice to the assigned officer. Request reinspection and written confirmation of the compliance date and case status. Ask separately about any fines or lien.',sources=['fl','pinellas','bradenton'],sections=[
section('before','Take useful before photos','''<p>Photograph the property before work begins, including every condition described in the notice. Use a wide view that shows location and close views that show the problem. Capture the front, rear, sides, fence lines and any cited right-of-way or swale.</p><p>Keep the original image files and their dates. Use truthful, unaltered photos for evidence. Do not digitally remove debris, shorten grass or replace parts of the image. Label a copy if useful, while keeping the original.</p><p>Make sure the work scope includes each cited condition. A beautifully mowed frontage will not prove that a backyard debris accumulation was removed.</p>'''),
section('after','Build the completion record','''<ul><li>Take after photos from the same positions as the before photos.</li><li>Show the entire area, with additional views for hidden corners.</li><li>Document the completion date and what work was performed.</li><li>Keep an invoice naming the property and describing mowing, brush work and removal.</li><li>Keep disposal or hauling records when relevant to the cited item.</li></ul><p>Our cleanup services include before/after photo documentation for the code officer. Confirm what the agency will accept; some cases still require an in-person reinspection.</p>'''),
section('send','Send a clear reinspection request','''<div class="sample-message"><p>Subject: Cleanup completed — Reinspection request — Case [number]</p><p>The cited cleanup at [property address] was completed on [date]. The work included [specific items]. Attached are dated before/after photographs and the work invoice.</p><p>Please arrange reinspection and confirm whether every cited item is in compliance. Please provide the recognized compliance date, written case status and any remaining fine, cost, hearing or lien requirements.</p><p>If anything remains, please identify the item and exact location so it can be addressed.</p></div><p>Use the official submission channel listed on the notice or department website. Keep a copy and a record of when you sent it.</p>'''),
section('close','Get the case status in writing',f'''<p>Ask the officer to distinguish “work appears complete,” “in compliance,” “case closed” and “lien released.” These descriptions are not interchangeable. Confirm whether a scheduled hearing is canceled or remains on the calendar.</p><p>Where a Part I compliance order was recorded and the order was met by its specified date, {cite('fl','§ 162.07(4)')} addresses a recorded order acknowledging compliance. If this applies to your case, ask about that record as well.</p><p>If daily fines were running, confirm the effective compliance date and updated balance. If a lien exists, follow the separate payoff or reduction and release process. Keep the written determination with your property records.</p>'''),
section('maintain','Keep it compliant through reinspection and beyond','''<p>Grass can regrow while you wait for a reinspection. Maintain the property and keep a local contact available if you live elsewhere. If debris has been removed, prevent new dumping where practical and inspect after storms or tenant turnover.</p><p>A recurring mowing schedule can reduce the chance of another violation. Set the interval based on growth and property conditions rather than waiting for a new warning letter.</p>''')]),

dict(slug='special-situations',label='Special ownership situations',title='When the property situation is complicated.',description='Overgrown-property notices for absentee owners, estates, rentals, vacant lots, pending sales, foreclosures and HOAs across Tampa Bay.',intro='You may be managing a property you do not live in—or one whose ownership and access are unsettled. Separate authority to arrange work from the government’s compliance deadline.',answer='Start by confirming the responsible party, who can authorize entry and which government or association issued the notice. Tell the officer about access or ownership obstacles promptly. They do not automatically suspend the case.',sources=['fl','hill_codes','pinellas','manatee_scope'],sections=[
section('absentee','Absentee and out-of-state owners','''<p>Verify the property address and parcel number, then obtain every page of the notice. Make sure the enforcing agency has a usable contact method for the responsible party. Do not assume that not seeing a posted notice means no deadline is running; Florida provides several notice methods in § 162.12.</p><p>Arrange a local contact, lawful gate access and a clearly defined scope. Ask for photos before authorizing work and after completion. Send the officer the evidence, request reinspection and keep the written outcome. Recurring maintenance is especially useful when no one is regularly checking the property.</p>'''),
section('estates','Inherited property and estates','''<p>Identify the personal representative or other person with legal authority to authorize the cleanup and contract for work. Give the officer a concise account of any probate or access issue and ask what documentation they need. A relative’s involvement alone does not establish authority.</p><p>Locate existing notices, balances and liens before assuming this is a new case. Keep invoices and communications with the estate records. For responsibility for a deceased owner’s debts, disputed title or probate deadlines, consult the estate’s lawyer.</p>'''),
section('rentals','Rentals: owner, tenant and manager','''<p>A lease may assign yard work to the tenant, but it does not necessarily determine whom the government can enforce against. Some ordinances impose duties on owners, occupants or other responsible persons. Read the cited section and the lease separately.</p><p>Notify the owner or manager promptly. Arrange lawful access and required tenant notice before a crew enters. Document the condition and agree on who is authorizing and paying for the work. We do not decide lease disputes or whether a particular entry is legally permitted.</p>'''),
section('vacant','Vacant lots and natural areas','''<p>Vacancy is not a general exemption from maintenance. At the same time, an overgrowth notice is not permission to clear every tree or wet area. Ask the officer to identify the affected portion and any applicable agricultural, conservation or landscaping exception.</p><p>Mark boundaries, identify soft ground, utilities and hidden dumping, and confirm disposal arrangements. Obtain any required permissions for protected resources before clearing. For ordinary mowing, the immediate goal is the cited condition, not a change to the land’s use or drainage.</p>'''),
section('sale','Under contract or in foreclosure',f'''<p>Give the title professional and buyer the known notices, orders and recorded-lien information early. Under {cite('fl','§ 162.06(5)')}, certain transfers during a pending enforcement proceeding have explicit disclosure and government-notification requirements. The case does not simply disappear when ownership changes.</p><p>A foreclosure filing does not by itself tell you who can authorize entry or who currently owns the property. Verify the records and obtain legal advice where necessary. {cite('hill_codes','Hillsborough County also has property-registration and preservation ordinances')} that may matter for a foreclosed or vacant property.</p><p>Set the cleanup date with time for reinspection and any title requirements. A contractor invoice is not a lien satisfaction.</p>'''),
section('hoa','HOA notices are a separate track',f'''<p>A homeowner association’s lawn notice generally arises from private governing documents and applicable law, not automatically from Chapter 162. HOA appearance requirements, deadlines, hearings and remedies can differ from city or county rules.</p><p>{cite('pinellas','Pinellas County')} and {cite('manatee_scope','Manatee County')} explicitly distinguish their code enforcement role from HOA enforcement. Correcting a government violation may still leave an HOA issue; satisfying the HOA may not close a government case.</p><p>Send completion evidence to each issuing body and obtain separate confirmations. Ask a Florida lawyer about disputed association fines, liens or enforcement rights.</p>''')])
]
