from content import S, cite, section

LOCAL = [
dict(slug='tampa', label='City of Tampa', county='Hillsborough County', title='An overgrown-property notice from the City of Tampa?',description='City of Tampa overgrowth help: Chapter 19, Neighborhood Enhancement, Code Enforcement Board hearings, civil citations and cleanup documentation.',intro='First, confirm that the notice says City of Tampa. A Tampa mailing address can also be in unincorporated Hillsborough County, where a different department and code apply.',answer='For a City of Tampa case, start with the Chapter 19 section on the notice and the assigned Neighborhood Enhancement officer. Confirm the required cleanup and deadline, then request reinspection. A civil citation under Chapter 23.5 has separate response requirements.',sources=['tampa_code','tampa','tampa_notice','tampa_board','tampa_cite','fl'],sections=[
section('rules','The Tampa code provisions to check',f'''<p>{cite('tampa_code','Chapter 19 of the Tampa Code')} addresses property maintenance and structural standards. Overgrowth-related notices can cite § 19-50, excessive undergrowth, and § 19-49, excessive accumulations of debris, rubbish, trash and related conditions. Read each section actually cited; the job may include removal as well as mowing.</p><p>{cite('tampa_notice','The city’s overgrown-lot guidance')} includes shrubs, trees, vines, bushes and weeds. This is not limited to a grass blade measured in the front yard. Ask the officer which conditions and which parts of the parcel require work.</p><p>We are not publishing a single Tampa height limit here because the current numeric scope was not independently confirmed from the accessible city code text. Use the current section linked above and your notice, or ask the officer to identify the applicable measurement. Do not substitute Pinellas County’s or another city’s rule.</p>'''),
section('office','Work with Neighborhood Enhancement',f'''<p>{cite('tampa','Neighborhood Enhancement')} identifies Chapters 19 and 27 among the ordinances it enforces. The department’s published general number is <a href="tel:+18132745545">813-274-5545</a>. This is the government office; call <a href="tel:+18136712757">813-671-2757</a> for our cleanup service.</p><p>Have the case number, address, notice date and compliance date ready. Ask whether the cited area includes any alley, sidewalk frontage or adjoining right-of-way. Do not assume the fence marks the full maintenance area or that a mowing notice authorizes protected-tree removal.</p>'''),
section('process','Board proceedings and court citations are different',f'''<p>{cite('tampa_board','Tampa’s Code Enforcement Board')} operates under Chapter 162 Part I and Tampa Code Chapter 9. If your case is set for that board, prepare photos, invoices and a concise chronology, and follow the hearing notice.</p><p>{cite('tampa_cite','Chapter 23.5')} separately establishes a Part II supplemental enforcement process with county-court jurisdiction for violations covered by that chapter. A citation lists payment and contest instructions. Finishing the yard does not by itself withdraw a ticket already issued.</p><p>For time extensions, identify whether you are asking to change an officer’s correction date or an ordered date. Keep the original date unless the authorized office confirms a change. Do not assume a hearing is canceled because work is scheduled.</p>'''),
section('cleanup','Your Tampa cleanup and closeout checklist','''<ul><li>List every Chapter 19 condition on the notice.</li><li>Confirm lawful access and any frontage or alley work.</li><li>Arrange mowing, brush work and removal needed for those conditions.</li><li>Photograph the same areas before and after.</li><li>Send the case number, invoice and completion photos to the assigned officer.</li><li>Request written compliance status and ask about any remaining hearing, fine or lien.</li></ul><p>We provide emergency overgrown-lot mowing, bush hogging, brush clearing and debris removal. Tell us the actual deadline when you <a href="/fix-my-violation/" data-request>request cleanup</a>; scheduling is confirmed after the work is reviewed.</p>''')]),

dict(slug='hillsborough-county',label='Hillsborough County',county='Unincorporated areas',title='Overgrowth notices in unincorporated Hillsborough County.',description='Hillsborough County overgrowth guidance: Property Maintenance Code PM 12.2, Special Magistrate and Board hearings, extensions and lien settlement.',intro='For Brandon, Riverview, Thonotosassa, Wimauma and other county addresses, confirm the parcel’s jurisdiction. Tampa, Temple Terrace and Plant City have their own municipal enforcement systems.',answer='Hillsborough County identifies overgrowth in its Property Maintenance Code as PM 12.2. The county’s property-maintenance program applies in unincorporated areas. Use the notice for the required correction and deadline, and arrange reinspection through County Code Enforcement.',sources=['hill','hill_code','hill_agenda','hill_board','hill_ceb','hill_lien','hill_codes','fl'],sections=[
section('rules','PM 12.2 and the county’s property-maintenance rules',f'''<p>{cite('hill','The county’s Property Maintenance Code guidance')} says the code regulates structures and properties in unincorporated Hillsborough County. It covers nuisance conditions including overgrowth, not just occupied houses.</p><p>The code is published in {cite('hill_code','Chapter 8, Article IV')}. Current county hearing materials identify <strong>PM 12.2: Overgrowth</strong> and distinguish it from <strong>PM 12.1: Accumulations</strong>. See the {cite('hill_agenda','2026 county agenda')} for the agency’s use of these provisions.</p><p>Check your copy of the code and notice for the applicable vegetation standard, affected area and exceptions. A current county-wide numeric height was not independently verified in the accessible code text for this guide, so we do not replace it with an assumed 10-, 12- or 18-inch rule.</p>'''),
section('contact','Contact the county, not a city based on the postal address',f'''<p>Hillsborough Code Enforcement’s published number is <a href="tel:+18132746600">813-274-6600</a>. Ask for the officer assigned to the case and have the folio or parcel number available if the address is ambiguous.</p><p>Confirm whether the notice requires the entire lot, a specific area, debris removal or other maintenance. Large parcels may have trees, wetlands or other features that require separate review. Do not equate an overgrowth correction with unrestricted land clearing.</p><p>{cite('hill_codes','The county also describes a property-preservation ordinance')} allowing abatement of serious nuisance conditions on vacant properties. Ask whether any abatement action has already been scheduled; booking private work does not automatically cancel a county work order.</p>'''),
section('hearings','Special Magistrate and Board processes',f'''<p>The county publishes both {cite('hill_board','Special Magistrate')} and {cite('hill_ceb','Code Enforcement Board')} hearing processes. Community-code hearings may be assigned by area. Use your actual notice and the current agenda rather than an old meeting location.</p><p>Request an extension before the stated deadline with a realistic completion date and proof of scheduled work. If an order already controls the date, ask whether the matter must return to the hearing body. Prepare dated photos and invoices even if the property has been cleaned before the hearing.</p>'''),
section('settlement','Hillsborough’s lien-settlement procedure',f'''<p>{cite('hill_lien','Hillsborough’s official settlement page')} requires the violations to be brought into compliance before settlement or release. The owner or authorized representative must submit the complete application with notarized signatures and supporting information through the designated channel.</p><p>The county distinguishes a payoff inquiry from a settlement application. It also describes potential hardship consideration for qualifying homesteaded properties. Visit the official page for submission instructions and current conditions; a cleanup invoice alone is not an application.</p><p>For immediate work, <a href="tel:+18136712757">call our cleanup line at 813-671-2757</a>. After completion, send the officer the documentation and get the compliance date in writing before addressing a remaining balance or lien.</p>''')]),

dict(slug='st-petersburg',label='St. Petersburg',county='Pinellas County',title='St. Petersburg overgrown-yard violations.',description='St. Petersburg vegetation maintenance under § 16.40.060.3.1: grass, rights-of-way, landscape exceptions, hearings and proof of cleanup.',intro='St. Petersburg has its own vegetation-maintenance code. Do not apply unincorporated Pinellas County’s lot-clearing rule just because the property is in Pinellas.',answer='St. Petersburg’s § 16.40.060.3.1 addresses vegetation maintenance, including the property and abutting rights-of-way. Its standards distinguish turf, ground cover and other planting. Check the exact subsection, any exception and the correction date on the city’s notice.',sources=['stpete_code','stpete_update','stpete_cases','stpete_budget','stpete_sm','fl'],sections=[
section('vegetation','The city’s vegetation-maintenance section',f'''<p>Start with {cite('stpete_code','St. Petersburg Code § 16.40.060.3.1')}. The city’s published {cite('stpete_update','Ordinance 611-H materials, amended at the July 10, 2025 hearing')}, include this section. The text sets a maximum overall height of 10 inches for sod and other herbaceous growth other than ground-cover species, and 24 inches for ground-cover plant material.</p><p>Those categories are important. A maintained ground-cover planting is not simply an unmowed lawn with a different label. The section also addresses maintenance plans for Florida-Friendly landscaping or wildlife habitat management and preservation-area treatment. Check the current code and ask the officer how any claimed exception applies to the actual parcel.</p><p>If your notice cites another subsection or an additional nuisance provision, address that item too. A single height measurement cannot answer every vegetation complaint.</p>'''),
section('edges','The maintenance area can include the right-of-way','''<p>The vegetation section places responsibilities on the owner of record and occupant for the property and abutting rights-of-way. Consider sidewalk edges, street corners and other cited frontage when reviewing the job.</p><p>Ask the officer to identify obstruction and clearance issues separately from turf height. Mowing does not fix a hedge blocking access or resolve every tree-related condition. A violation notice does not remove the need to check applicable protections or permissions before tree work.</p><p>Collect and dispose of debris properly. Do not blow cut material into the street or drainage system while trying to correct an overgrown yard.</p>'''),
section('case','Find the city case and hearing assignment',f'''<p>Use the {cite('stpete_cases','city’s official case-search application')} and the contact information on the notice. Confirm that the parcel is within St. Petersburg city limits. Lealman and other unincorporated areas may have a St. Petersburg postal address but a county case.</p><p>{cite('stpete_budget','The city’s FY 2026 materials')} describe Code Enforcement Board, Special Magistrate, civil-citation and county-court enforcement processes. Your document determines which applies. The {cite('stpete_sm','Special Magistrate rules')} are a useful starting point for preparation; verify current evidence and attendance instructions for your hearing.</p><p>If you need more time, request a specific date and provide a work plan. If you have already received an order or citation, ask what formal action is required rather than assuming an informal call changes it.</p>'''),
section('proof','Document every cited area','''<p>For the work record, photograph the lawn and any abutting area that the notice identifies. Include the sidewalk edge, hedge or ground-cover area when relevant. Keep the original dated files and the work invoice.</p><p>Send the evidence with the city case number and request reinspection. Ask for written confirmation of compliance, the recognized date and whether a hearing or balance remains. If there is a recorded lien, obtain separate instructions for resolving and releasing it.</p><p><a href="/fix-my-violation/" data-request>Request cleanup help</a> or <a href="tel:+18136712757">call 813-671-2757</a>. We can mow, clear underbrush, remove debris and document the completed work; the city makes the compliance determination.</p>''')]),

dict(slug='clearwater',label='Clearwater',county='Pinellas County',title='Clearwater overgrowth and nuisance notices.',description='Clearwater § 3-1503.B.7 overgrowth and B.8 right-of-way maintenance explained, with city hearing information and a cleanup documentation checklist.',intro='Clearwater’s Community Development Code addresses overgrowth and unmaintained rights-of-way as distinct nuisance conditions. Check whether your notice includes both.',answer='Clearwater § 3-1503.B.7 addresses excessive growth over 12 inches and debris accumulation. Section 3-1503.B.8 separately addresses unmaintained abutting rights-of-way. Follow the city’s notice for the exact areas and deadline.',sources=['clearwater_code','clearwater_affidavit','clearwater','clearwater_board','clearwater_guide','fl'],sections=[
section('code','The city’s nuisance sections',f'''<p>In the {cite('clearwater_code','Clearwater Community Development Code')}, § 3-1503.B.7 covers excessive weeds, grass, undergrowth or similar plant material reaching more than 12 inches, as well as accumulation of debris. The city’s {cite('clearwater_affidavit','2026 enforcement affidavit')} quotes that provision and § 3-1503.B.8 for unmaintained right-of-way conditions.</p><p>This is a city standard, not the Pinellas County standard for unincorporated land. Confirm the issuing government even when the mailing address is Clearwater.</p><p>Ask which specific conditions remain if the yard has already been partly mowed. Debris, an unmaintained strip or another cited nuisance can keep the case open after most of the grass is cut.</p>'''),
section('right-of-way','Include the abutting maintenance area','''<p>Review the sidewalk, curbside strip and other frontage mentioned on the notice. Ask the inspector where the required area starts and ends, especially if the parcel adjoins multiple streets or the boundary is unclear.</p><p>Do not assume mowing inside the fence is enough. At the same time, do not cut a neighbor’s property or alter a drainage area without confirming authority and scope. Photograph any access, utility or drainage obstacle and raise it before the deadline.</p>'''),
section('hearing','Municipal Code Enforcement Board and other routes',f'''<p>Clearwater publishes a {cite('clearwater_board','Municipal Code Enforcement Board')} process. Its {cite('clearwater_guide','citizen handbook')} also identifies Special Magistrate and court enforcement options. Read the actual hearing or citation notice to identify your forum and response requirements.</p><p>{cite('clearwater','The city’s enforcement guidance')} explains that case timing varies with the owner’s response and hearing schedules. There is no single guaranteed resolution time. Ask the assigned inspector about an extension before the correction date if you cannot complete the required scope.</p><p>Use the current meeting notice for the location and time. Bring completion photographs and the invoice, and verify whether the hearing is still required after the cleanup.</p>'''),
section('next','A practical Clearwater response','''<ol><li>Match the address and case number to the city notice.</li><li>Mark each item under § 3-1503, including any right-of-way item.</li><li>Confirm the mowing, brush and debris-removal scope.</li><li>Arrange access and a work date; contact the inspector if timing is a problem.</li><li>Send dated before/after photos and request written reinspection findings.</li></ol><p>If the city has already assessed fines or recorded a lien, ask for a current balance and the applicable reduction or release process. A clean property is evidence of correction, not automatic proof of a zero balance.</p><p>For cleanup in Clearwater, <a href="tel:+18136712757">call 813-671-2757</a> or <a href="/fix-my-violation/" data-request>send the property details</a>.</p>''')]),

dict(slug='pinellas-county',label='Pinellas County',county='Unincorporated areas, including Lealman',title='Overgrown-property notices in unincorporated Pinellas.',description='Pinellas County grass and weeds, § 58-331, debris rules, government lot clearing, Special Magistrate hearings and lien reduction—including Lealman.',intro='Lealman and other unincorporated communities use county code enforcement. Incorporated cities and the beach towns may have their own standards and procedures.',answer='Pinellas County’s official guidance identifies grass and weeds reaching 12 inches over the majority of the property as a § 58-331 violation. The county may hire a cleanup contractor after noncompliance and place an interest-accruing lien for the costs.',sources=['pinellas','pinellas_code','pinellas_sm','pinellas_lien','fl'],sections=[
section('scope','Confirm county jurisdiction first',f'''<p>{cite('pinellas','Pinellas County Code Enforcement')} says it investigates county-ordinance violations in unincorporated areas. Its official page links to a jurisdiction lookup. A St. Petersburg or Clearwater mailing address is not conclusive evidence that a city issued the case.</p><p>If the notice names a city, use that city’s code and enforcement office. County rules should not be copied onto Pinellas Park, Largo, Seminole or a beach municipality without checking jurisdiction.</p><p>For a county case, the published Code Enforcement number is <a href="tel:+17274644761">727-464-4761</a>. Our separate cleanup line is <a href="tel:+18136712757">813-671-2757</a>.</p>'''),
section('rules','Grass, weeds and debris',f'''<p>{cite('pinellas','The county’s yard-maintenance summary')} states that developed properties must be maintained whether occupied or vacant. It identifies the 12-inch, majority-of-property condition under {cite('pinellas_code','§ 58-331')} and separately addresses trash and debris under § 58-304.</p><p>That summary is not a substitute for the full lot-clearing article and its definitions. Ask how the rule applies to a particular undeveloped parcel or natural area. Do not assume any isolated plant above 12 inches makes an otherwise maintained landscape a violation.</p><p>A case may require both mowing and removal of accumulated materials. Walk the whole cited area before quoting work, including debris that the growth may hide.</p>'''),
section('abatement','The county can arrange the cleanup and bill for it',f'''<p>The county explains that it may notify the owner or responsible party, post the property and courthouse, then hire a contractor if mowing and removal are not completed. The costs can become an interest-accruing lien.</p><p>Read an abatement notice immediately. Ask whether a county work order has been issued and how to report private completion before the contractor is dispatched. Do not assume a cleanup booking or a pending extension request stops abatement.</p><p>The local lot-clearing process can differ from a Chapter 162 administrative fine case. Ask whether the file involves a mowing-cost lien, daily fines or both before deciding what must be paid or reduced.</p>'''),
section('hearings','Special Magistrate and lien reduction',f'''<p>{cite('pinellas_sm','Pinellas County uses Special Magistrates')} for administrative code hearings. Prepare the case-specific evidence and check the current hearing notice. A completed cleanup does not automatically cancel a scheduled hearing.</p><p>{cite('pinellas_lien','The county’s lien-reduction page')} offers review for eligible compliant property owners and also mentions prospective new owners of noncompliant property. Eligibility for review is not approval. Submit the requested information and obtain written terms before relying on a reduced figure for a closing.</p><p>After our cleanup, send dated photos and the invoice, request reinspection and obtain the recognized compliance date. Ask separately for the balance and recorded release requirements.</p>''')]),

dict(slug='bradenton',label='Bradenton',county='Manatee County',title='City of Bradenton overgrown-property notices.',description='Bradenton city property maintenance under §§ 18-240–18-241: vegetation standards, Special Magistrate and citation processes, and cleanup closeout.',intro='Bradenton city enforcement is separate from Manatee County enforcement. Confirm the government named on the notice before relying on a county grass-height summary.',answer='Bradenton adopts and locally revises a property maintenance code through §§ 18-240 and 18-241. Those local amendments matter. Contact the assigned city officer to confirm the vegetation standard, work area and deadline; the city uses both a Special Magistrate and citations.',sources=['bradenton','bradenton_code','bradenton_amend','bradenton_sm','fl'],sections=[
section('code','Local amendments change the property-maintenance standard',f'''<p>{cite('bradenton_code','Bradenton Code §§ 18-240 and 18-241')} govern adoption and local revisions of the property maintenance code. The city’s published {cite('bradenton_amend','Ordinance 3096 materials')} identify a local revision to the weeds provision, IPMC § 302.4.</p><p>Do not assume the unamended International Property Maintenance Code—or Manatee County’s 16-inch guidance—is the rule for a Bradenton city parcel. The city’s local revisions distinguish grass-type ground cover from other weeds.</p><p>The accessible amendment materials are not a substitute for verifying the currently applied, consolidated text. We therefore do not publish a single numeric Bradenton mowing threshold here. Ask the city officer to identify the current § 302.4 standard as locally revised and any additional provision on your notice.</p>'''),
section('contact','Use the city’s case contact',f'''<p>{cite('bradenton','Bradenton Code Enforcement')} directs owners to the officer identified on the notice for case-specific questions. Its published coordinator number is <a href="tel:+19419329485">941-932-9485</a>.</p><p>Ask which conditions require correction and whether the citation includes debris or other property-maintenance issues. Record the original compliance date, any hearing date and the case number before arranging work.</p><p>If you live outside the area or manage an estate or rental, explain access and authority issues early. Provide a concrete work plan if requesting more time; a phone message is not an approved extension.</p>'''),
section('process','Special Magistrate and citation routes',f'''<p>The city states that it uses a {cite('bradenton_sm','Special Magistrate')} and a citation process. Noncompliance may result in fines or citations. A Magistrate hearing notice and a county-court citation call for different responses, even if both concern the same yard.</p><p>For a hearing, bring the notice, dated photos, invoice and communications. For a citation, follow its payment or contest directions and consult a lawyer if you want to challenge liability. Do not assume payment arranges the physical cleanup or that cleanup dismisses an issued citation.</p><p>Check the current notice and city meeting information for attendance instructions. Do not rely on a routine monthly schedule when a particular case has been continued or specially set.</p>'''),
section('completion','Finish the work and the paperwork','''<p>Ask the officer to identify any frontage, swale or separate accumulation item. Arrange mowing or bush hogging appropriate to the growth, brush clearing where needed, and lawful debris removal. Keep protected vegetation and access limitations in the scope discussion.</p><p>After work, provide matching before/after photos and the invoice with the case number. Request reinspection and written confirmation of compliance. Ask whether a fine, lien or hearing remains and which city process addresses it.</p><p><a href="tel:+18136712757">Call 813-671-2757</a> for cleanup availability in Bradenton, or <a href="/fix-my-violation/" data-request>send the notice details</a>. We handle the property work and documentation; the city determines compliance.</p>''')]),

dict(slug='manatee-county',label='Manatee County',county='Unincorporated areas',title='Manatee County overgrown-yard violations.',description='Manatee County overgrowth guidance: 16-inch county guidance, § 2-9-103 definitions, courtesy notices, citations, Special Magistrate and compliance photos.',intro='For Parrish, Ellenton and other county locations, check the parcel and the notice. Bradenton and Palmetto are separate municipalities; a postal address alone does not decide which rules apply.',answer='Manatee County’s official guidance says grass must be kept under 16 inches and links to § 2-9-103 in its Property Maintenance and Structural Standards article. Use the exact cited provision and notice to confirm the affected area, exceptions and correction deadline.',sources=['manatee','manatee_code','manatee_process','manatee_sm','manatee_scope','fl'],sections=[
section('rule','The county’s height guidance and code definitions',f'''<p>{cite('manatee','Manatee County’s Code Enforcement Do’s and Don’ts')} tells owners to keep grass under 16 inches. Its overgrown-yard link points to {cite('manatee_code','§ 2-9-103, definitions in Chapter 2-9, Article VI')}. Read that article together with the substantive section cited on your notice.</p><p>The same official guidance treats trash, debris and outdoor storage as separate concerns. An overgrown parcel may have more than one item to correct. Do not assume a mowing pass resolves a storage or debris violation.</p><p>For a large or partly natural lot, ask the officer about the area to be maintained and applicable exceptions. An overgrowth case is not blanket authorization to disturb wetlands, conservation areas or protected trees.</p>'''),
section('jurisdiction','County enforcement serves unincorporated areas',f'''<p>{cite('manatee_scope','The county’s Code Enforcement 101 page')} describes its unincorporated service area and distinguishes code enforcement from HOA enforcement. Verify the issuing government before choosing an office or code standard.</p><p>Use the assigned officer’s number on the notice for case questions. Give the parcel number if the location is a vacant lot, has no clear street number or is close to a municipal boundary. For cleanup service, our number is <a href="tel:+18136712757">813-671-2757</a>.</p>'''),
section('stages','The county explains several possible enforcement paths',f'''<p>{cite('manatee_process','Manatee’s published case-process guidance')} describes an initial courtesy notice, often a door hanger, followed by a formal notice if the condition is not resolved. It then identifies a citation, a notice to appear in court or a referral to a Special Magistrate as possible next steps.</p><p>That local description does not guarantee a courtesy stage in every circumstance. Repeat violations and serious conditions can be handled differently under state law. Follow the date printed on the actual document rather than assuming a standard grace period.</p><p>The county’s process page gives examples of daily fine amounts after Magistrate proceedings. Those examples are not a substitute for the rate in your own order or the applicable legal limits. Request the order and an itemized balance if fines are already running.</p>'''),
section('hearing','Prepare for the Special Magistrate',f'''<p>{cite('manatee_sm','Manatee County’s Special Magistrate')} holds hearings and can impose fines under the county’s enforcement system. If a hearing is scheduled, prepare the notice, a dated work chronology, before/after photos and invoices.</p><p>Ask about extensions before the compliance date. If a Magistrate order already sets the date, find out whether a formal request must be heard. Keep attending to the original deadline unless an authorized decision changes it.</p>'''),
section('close','Get a written compliance determination','''<p>Send the officer the completed-work photos and invoice with the address and case number. Request reinspection, written compliance status and the effective compliance date. Confirm whether any court appearance or administrative hearing remains.</p><p>For an outstanding fine or lien, request the current county instructions for reduction, payment and release. Neither mowing nor paying a contractor automatically releases a government lien.</p><p><a href="/fix-my-violation/" data-request>Request mowing, brush clearing or debris removal</a> and include the deadline. We also offer recurring maintenance to help keep the same conditions from returning.</p>''')])
]

FAQ = [
('How long do I have to fix an overgrown yard violation in Tampa?', 'Use the compliance date on the City of Tampa notice. Florida’s ordinary Part I process calls for a reasonable correction period, not one universal mowing deadline. If the document is a citation, court notice or abatement notice, its separate instructions matter.', '/local-codes/tampa/', 'tampa_code'),
('Is there one grass-height limit for all of Tampa Bay?', 'No. City and county ordinances differ, and some distinguish turf, ground cover, natural areas and the portion of a parcel affected. Confirm the issuing jurisdiction and cited section before using a number from another community.', '/guides/what-counts-as-overgrown/', 'pinellas'),
('What is the grass-height rule in unincorporated Pinellas County?', 'The county’s official yard-maintenance guidance identifies grass and weeds reaching 12 inches over the majority of the property as a violation of § 58-331. Read the full code and notice for scope and exceptions.', '/local-codes/pinellas-county/', 'pinellas'),
('What is the overgrown-grass guidance in Manatee County?', 'Manatee County’s official guidance says grass must be kept under 16 inches. This is county guidance; a Bradenton or Palmetto city parcel may have a different standard. Confirm the exact section and area listed on the notice.', '/local-codes/manatee-county/', 'manatee'),
('Can the county mow my lot and charge me?', 'Yes, where the applicable abatement law and notice procedure authorize it. Pinellas County explicitly describes hiring a cleanup contractor and placing an interest-accruing lien for the costs. An abatement charge can be separate from administrative fines.', '/guides/enforcement-timeline/', 'pinellas'),
('Can I get more time to clean up the property?', 'You can request an extension, but approval is not automatic. Contact the assigned officer before the deadline, propose a specific completion date and provide documentation. Ask who can change the date if a board, Magistrate or court has already entered an order.', '/guides/request-an-extension/', 'fl'),
('Does hiring a mowing company stop the deadline?', 'No. Booking work is evidence of a plan, not government approval of a new deadline. Continue using the original date unless the authorized office confirms a change.', '/guides/request-an-extension/', 'fl'),
('How much can code enforcement fine me per day?', 'The standard Florida Part I ceilings are $250 per day for a first violation and $500 per day for a repeat violation. Qualifying local governments can adopt higher limits. The actual authority and order in your case determine the rate.', '/guides/fines-and-costs/', 'fl'),
('Do fines stop automatically when I mow?', 'Part I fine accrual is tied to compliance or the statutory judgment event, but the date of compliance must be established. Notify the officer immediately, provide evidence and get the recognized date in writing. Existing fines and costs are not automatically erased.', '/guides/proving-compliance/', 'fl'),
('What makes someone a repeat violator?', 'For Part I, § 162.04(5) looks to a prior finding of violation of the same code provision within five years, even at a different location. A local civil-citation process may define repeat violations differently.', '/guides/fines-and-costs/', 'fl'),
('Do I still have to attend a hearing if the yard is clean?', 'Possibly. A case may still be heard after late correction or in a repeat case. Contact the hearing office and get confirmation of any cancellation. Do not skip a scheduled hearing merely because you sent photographs.', '/guides/hearings-and-appeals/', 'fl'),
('What should I bring to a code enforcement hearing?', 'Bring all notice pages, the case number, a short chronology, dated before/after photos, invoices and relevant correspondence. Confirm the evidence-submission rules in advance; photos on your phone may not be enough.', '/guides/hearings-and-appeals/', 'fl'),
('What is the difference between a Special Magistrate and a Code Enforcement Board?', 'A Special Magistrate is an individual administrative hearing officer; a Code Enforcement Board is a panel. Local law determines the assignment. Both are distinct from the county-court process for a civil citation.', '/guides/hearings-and-appeals/', 'fl'),
('Can I appeal a code enforcement order?', 'Section 162.11 provides an appeal of a final Part I administrative order to circuit court within 30 days of execution of the order. Review is based on the administrative record, not a new trial. Seek legal advice promptly about your deadline and procedure.', '/guides/hearings-and-appeals/', 'fl'),
('Is a civil citation the same as a notice of violation?', 'No. A notice generally identifies corrective work and a deadline. A civil citation has payment or contest instructions and may be handled in county court. Read and respond to those instructions separately from arranging cleanup.', '/guides/civil-citations/', 'fl'),
('Will cutting the grass cancel an issued citation?', 'Not automatically. Ask the issuing office about the citation status and follow any court instructions. Cleanup, dismissal, payment and administrative case closure are separate events.', '/guides/civil-citations/', 'tampa_cite'),
('Can I get my code enforcement fine reduced?', 'You may request a reduction through the applicable local process. Section 162.09 allows fine reduction but does not guarantee it. Document compliance and corrective effort, and obtain the decision and payment terms in writing.', '/guides/liens-and-fine-reductions/', 'fl'),
('Does the lien disappear after the property is cleaned?', 'No. Compliance does not by itself satisfy or release a recorded lien. Request an itemized payoff or reduction review and confirm that any required satisfaction or release is recorded.', '/guides/liens-and-fine-reductions/', 'fl'),
('Can an overgrown-property lien affect selling or refinancing?', 'It can. Give the notices and recorded-lien information to your title professional or closing agent early. Obtain current payoff and release instructions; a cleanup invoice is not a complete title clearance.', '/guides/liens-and-fine-reductions/', 'fl'),
('Can the government foreclose a code enforcement lien?', 'Florida Part I permits authorized foreclosure or collection proceedings after an unpaid lien has been recorded for three months, with important constitutional homestead protections. It is not automatic, and other assessment types require separate analysis. Get legal advice if collection is threatened.', '/guides/liens-and-fine-reductions/', 'fl'),
('Does my tenant have to fix the yard violation?', 'The lease may assign mowing, but the ordinance determines whom the government may enforce against. Owners or occupants may have duties. Coordinate lawful access and payment with the owner or manager rather than assuming the lease closes the government case.', '/guides/special-situations/', 'stpete_code'),
('What if I live out of state or inherited the property?', 'Confirm who can authorize the work, obtain the full notice and contact the officer promptly about access or estate issues. Arrange before/after documentation and a local contact. Ownership or distance complications do not automatically pause enforcement.', '/guides/special-situations/', 'fl'),
('Do vacant lots have to be maintained?', 'Often, yes, but the rule can depend on development status, zoning, parcel conditions and exceptions. Ask which area must be maintained. An overgrowth notice does not authorize unrestricted clearing of protected natural areas.', '/guides/what-counts-as-overgrown/', 'pinellas'),
('Do I have to mow the swale or strip outside my fence?', 'Possibly. Some local rules place duties on the abutting owner or occupant. Ask the officer to identify the maintenance area and confirm any drainage or access restrictions before work.', '/guides/what-counts-as-overgrown/', 'clearwater_affidavit'),
('Are HOA violations handled by county code enforcement?', 'Generally, HOA requirements are a separate private enforcement track. Pinellas and Manatee counties say they do not enforce HOA rules. If both an association and government issued notices, request separate confirmations after cleanup.', '/guides/special-situations/', 'pinellas'),
('How do I prove the violation has been corrected?', 'Send the case number, address, dated before/after photos and invoice to the assigned officer. Request reinspection and written confirmation of the compliance date, remaining obligations and case status.', '/guides/proving-compliance/', 'fl'),
('Can you help if my deadline is this week?', 'Call 813-671-2757 to discuss the deadline, property condition and availability. Emergency overgrown-lot mowing is one of our services, but a work date must be confirmed after the scope and access are reviewed.', '/fix-my-violation/', None),
('What services do you provide?', 'Emergency overgrown-lot mowing, bush hogging, brush and underbrush clearing, debris and yard-waste removal, before/after photo documentation for the code officer, and recurring maintenance.', '/services/', None),
('Are you the government or a law firm?', 'No. Fix My Violation is a property cleanup company. The guides provide general information, not legal advice. We do not issue notices, extend government deadlines, dismiss citations or decide whether a case is closed.', '/services/', None),
('Do I need the case number before requesting cleanup?', 'No. It is helpful but optional. Provide the property address, issuing government if known and the deadline. You can add a photo of the notice when online uploads are available, or call to discuss the details.', '/fix-my-violation/', None)
]
